spring:
  application:
    name: current-account
  datasource:
    driver-class-name: 'org.h2.Driver'
    url: 'jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;IGNORECASE=TRUE;'
    username: 'sa'

  liquibase:
    change-log: 'db/liquibase-changeLog.xml'
  jpa:
    defer-datasource-initialization: false
    show-sql: true
    properties:
      hibernate:
        ddl-auto: 'create-drop'
    database-platform: 'org.hibernate.dialect.H2Dialect'
  h2:
    console:
      enabled: true